name = "High Roller"
author = "Charliemineboy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7115610e232bbb4b5aca297b01d7f7021c242a71e3eb557c9bea3037dd987d6"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
