name = "High Roller"
author = "Charliemineboy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fafef1089eafa6a7213c6331978953209482d23fcbd0145de2a815ca41bd767c"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
