name = "High Roller"
author = "Charliemineboy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9cbfdaa7a705ce734036222be464753153ac14cd76c717f5feda629d3652cfb"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
