name = "High Roller"
author = "Charliemineboy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7368f82fdc63416f8a1a05729d9b0ecea4d0ffc1a2fcc09de51fa01731e7720"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
