name = "High Roller"
author = "Charliemineboy and ItsPercent"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ae7745283379d0058740f262f7ed8237b4e40ccc754792bd5037c9b67f5e46c"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
