name = "High Roller"
author = "Charliemineboy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57da672e2511094492d904727e860b6490149a0ee1282a24109afebe08cba4ea"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
